services:
  withpark-server:
    container_name: withpark-server
    build: .
    ports:
      - "50001:8080"
    depends_on:
      - withpark-postgres
    networks:
      - withpark-network
  withpark-postgres:
    image: postgres:15.15
    container_name: withpark-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: withpark
      POSTGRES_USER: withpark
      POSTGRES_PASSWORD: withpark123
      TZ: Asia/Seoul
    volumes:
      - withpark-database:/var/lib/postgresql/data
    networks:
      - withpark-network
volumes:
  withpark-database:

networks:
  withpark-network:
    driver:
      bridge
