services:
  withpark-server:
    container_name: withpark-server
    build: .
    ports:
      - "${PROD_SERVER_PORT}:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - withpark-postgres
    networks:
      - withpark-network
  withpark-postgres:
    image: postgres:15.15
    container_name: withpark-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TIMEZONE}
    volumes:
      - withpark-database:/var/lib/postgresql/data
    networks:
      - withpark-network
volumes:
  withpark-database:

networks:
  withpark-network:
    driver:
      bridge
