spring:
  application:
    name: withpark
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://withpark-postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: debug
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
server:
  port: ${PROD_SERVER_PORT:8080}
kakao:
  REST_API_KEY: ${KAKAO_REST API KEY}
  REDIRECT_URI: ${KAKAO_REDIRECT_URI}
  OAUTH_CALLBACK_URI: ${KAKAO_OAUTH_CALLBACK_URI}
naver:
  CLIENT_ID: ${NAVER_CLIENT_ID}
  CLIENT_SECRET: ${NAVER_CLIENT_SECRET}
  REDIRECT_URI: ${NAVER_REDIRECT_URI}
  OAUTH_CALLBACK_URI: ${NAVER_OAUTH_CALLBACK_URI}
jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000