spring:
  application:
    name: withpark
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://withpark-postgres:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
logging:
  level:
    root: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: info
server:
  port: ${PROD_SERVER_PORT:8080}
kakao:
  REST_API_KEY: ${KAKAO_REST API KEY}
  REDIRECT_URI: ${KAKAO_REDIRECT_URI}