spring:
  application:
    name: withpark
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    user:
      name: disabled
      password: disabled
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springdoc: debug
server:
  port: ${DEV_SERVER_PORT:8080}
kakao:
  REST_API_KEY: ${KAKAO_REST API KEY}
  REDIRECT_URI: ${KAKAO_REDIRECT_URI}
  OAUTH_CALLBACK_URI: ${KAKAO_OAUTH_CALLBACK_URI}
jwt:
  access-secret: ${JWT_ACCESS_SECRET}
  refresh-secret: ${JWT_REFRESH_SECRET}
  access-token-expiration: 3600000
  refresh-token-expiration: 604800000
upload:
  path: uploads
  url: http://localhost:${DEV_SERVER_PORT:8080}/uploads